/*
	WRCNFGGL.i
	Copyright (C) 2007 Paul C. Pratt

	You can redistribute this file and/or modify it under the terms
	of version 2 of the GNU General Public License as published by
	the Free Software Foundation.  You should have received a copy
	of the license along with this file; see the file COPYING.

	This file is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	license for more details.
*/

/*
	WRite "CNFGGLob.h"
		(renamed to "CNFUIALL.h")
*/


LOCALPROC WriteConfigurationWarning(void)
{
	WriteBlankLineToDestFile();
	WriteDestFileLn(
		"This file is automatically generated by the build system,");
	WriteDestFileLn(
		"which tries to know what options are valid in what");
	WriteDestFileLn(
		"combinations. Avoid changing this file manually unless");
	WriteDestFileLn(
		"you know what you're doing.");
}

LOCALPROC WriteCommonCNFUIALLContents(void)
{
	WriteDestFileLn("/*");
	++DestFileIndent;
		WriteDestFileLn(
			"see comment in OSGCOMUI.h");
		WriteConfigurationWarning();
	--DestFileIndent;
	WriteDestFileLn("*/");

	WriteBlankLineToDestFile();
	WriteDestFileLn("/* adapt to current compiler/host processor */");

	/*
		There used to be a bitness sanity check emitted here, but it
		only ever covered x86/x64/ppc/ppc64. There was no a64 case, so
		an Apple Silicon build emitted nothing.
	*/

	WriteBlankLineToDestFile();

#if NeedIntFormatInfo
	/*
		These were derived from the CPU family table, which had no a64
		entry, so an Apple Silicon build answered false to all three.
		NeedIntFormatInfo is off for this emulator anyway.
	*/
	WriteCompCondBool("MostSigByteFirst", falseblnr);
	WriteCompCondBool("LeastSigByteFirst", falseblnr);
	WriteCompCondBool("TwosCompSigned", falseblnr);
#endif

	WriteDestFileLn(
		"#define MayInline inline __attribute__((always_inline))");

	WriteDestFileLn(
		"#define MayNotInline __attribute__((noinline))");

	/*
		ARM64 code generation hints. The only host is arm64 clang,
		so these hold for every build and are no longer gated
		on -ob.
	*/
	WriteDestFileLn("#define BigEndianUnaligned 0");
	WriteDestFileLn("#define LittleEndianUnaligned 1");

	WriteDestFileLn("#define my_cond_rare(x) "
		"(__builtin_expect(x, 0))");
	WriteDestFileLn("#define Have_ASR 1");

	WriteDestFileLn("#define HaveUi6Div 1");

	/*
		No HaveGlbReg (or r_pc_p, see SPOTHRCF.i). A global
		register variable is only sound if nothing else ever
		uses that register, but AArch64 has no callee-reserved
		register to give it: x15 (and every other candidate)
		is caller-saved scratch that system frameworks, Swift
		and the compiler's own calls freely clobber, so the
		emulated pc would be corrupted across any host call.
	*/

	WriteDestFileLn(
		"#define my_align_8 __attribute__ ((aligned (8)))");

	WriteCompCondBool("SmallGlobals", falseblnr);
		/* only the 68k hosted build ever wanted small globals */

	WriteDestFileLn("#define cIncludeUnused 0");

	WriteDestFileLn("#define UnusedParam(p) (void) p");

	WriteBlankLineToDestFile();
	WriteDestFileLn("/* --- integer types ---- */");

	/*
		define signed and unsigned integer types
		for 8 bits, 16 bits, 32 bits, and so on.

		the computer might not have integer types
		of a given size. in this case should define
		a type of correct size, such as a structure
		type, even if the computer can't directly do
		integer operations on it. then set
		HaveReal?i?b to 0.
	*/

	/* 8 bits */

	/* (ui3b)0 - (ui3b)1 == (ui3b)255 */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef unsigned char ui3b;");
	WriteDestFileLn("#define HaveRealui3b 1");

	/* sizeof(si3b) == sizeof(ui3b) */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef signed char si3b;");
	WriteDestFileLn("#define HaveRealsi3b 1");

	/* 16 bits */

	/* (ui4b)0 - (ui4b)1 == (ui4b)65535 */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef unsigned short ui4b;");
	WriteDestFileLn("#define HaveRealui4b 1");

	/* sizeof(si4b) == sizeof(ui4b) */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef short si4b;");
	WriteDestFileLn("#define HaveRealsi4b 1");

	/* 32 bits */

	/* (ui5b)0 - (ui5b)1 == (ui5b)4294967295 */
	/* on a 64 bit target, "long" is 64 bits, so use "int" */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef unsigned int ui5b;");
	WriteDestFileLn("#define HaveRealui5b 1");

	/* sizeof(si5b) == sizeof(ui5b) */
	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef int si5b;");
	WriteDestFileLn("#define HaveRealsi5b 1");

	/* 64 bits */ /* real types are emitted by Write64bitConfig */
	WriteBlankLineToDestFile();
	WriteDestFileLn("#define HaveRealui6b 0");
	WriteDestFileLn("#define HaveRealsi6b 0");

	WriteBlankLineToDestFile();
	WriteDestFileLn("/* --- integer representation types ---- */");

	/*
		for each integer type, define
		the most efficient representation
		for parameter passing and temporary
		variables on the current
		computer.
	*/

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef ui3b ui3r;");
	WriteDestFileLn("#define ui3beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef si3b si3r;");
	WriteDestFileLn("#define si3beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef ui4b ui4r;");
	WriteDestFileLn("#define ui4beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef si4b si4r;");
	WriteDestFileLn("#define si4beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef ui5b ui5r;");
	WriteDestFileLn("#define ui5beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn("typedef si5b si5r;");
	WriteDestFileLn("#define si5beqr 1");

	WriteBlankLineToDestFile();
	WriteDestFileLn(
		"#define MySwapUi5r(x)"
		" ((ui5r)__builtin_bswap32(x))");
	WriteDestFileLn("#define HaveMySwapUi5r 1");
}

LOCALPROC Write64bitConfig(void)
{
	WriteBlankLineToDestFile();
	{
		WriteDestFileLn("typedef signed long long si6r;");
		WriteDestFileLn("typedef signed long long si6b;");
		WriteDestFileLn("typedef unsigned long long ui6r;");
		WriteDestFileLn("typedef unsigned long long ui6b;");
		WriteDestFileLn("#define LIT64(a) a##ULL");
	}
}
