/*
	EMUCTLAP.h

	Copyright (C) 2026 Moof contributors

	You can redistribute this file and/or modify it under the terms
	of version 2 of the GNU General Public License as published by
	the Free Software Foundation.  You should have received a copy
	of the license along with this file; see the file COPYING.

	This file is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	license for more details.
*/

/*
	EMUlator ConTroL Api

	The narrow surface that the Swift side of the user interface is
	allowed to touch. Everything here is plain C using plain C types,
	so that Swift sees Int32 and Bool rather than the ui3b and blnr
	aliases used throughout the emulator.

	Every function here takes the emulator lock itself, so the Swift
	side can never forget to. The lock is recursive, so it is safe to
	call these from a main thread path that already holds it, such as
	the display link handler.

	Scope is deliberately limited to state the emulator can change
	while running. The machine model, memory size, screen dimensions
	and colour depth are fixed when the build is generated by
	setuptool and are not exposed, because nothing here could honour
	a change to them.

	Unlike most headers in this directory, this one is included from
	more than one translation unit, so it uses an ordinary include
	guard rather than the "header already included" error guard that
	the unity build headers use.

	Nothing here may pull in a unity build header such as CONTROLM.h
	or COMOSGLU.h. Those are implementation, included exactly once
	into the backend, and a second inclusion is a hard error.
*/

#ifndef EMUCTLAP_H
#define EMUCTLAP_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
	Which optional features this build was generated with. The
	interface asks rather than assuming, so that a build made without
	magnification or without sound does not offer controls that
	cannot do anything.
*/
extern bool MNVM_HasMagnify(void);
extern bool MNVM_HasFullScreen(void);
extern bool MNVM_HasSound(void);

/*
	Speed as an exponent: 0 is 1x, 5 is 32x. kMNVMSpeedAllOut means
	run as fast as the host allows.
*/
#define kMNVMSpeedAllOut (-1)

extern int MNVM_GetSpeedValue(void);
extern void MNVM_PostSetSpeedValue(int v);

extern bool MNVM_GetSpeedStopped(void);
extern void MNVM_PostSetSpeedStopped(bool v);

/* Runtime toggles. */
extern bool MNVM_GetMagnify(void);
extern void MNVM_PostSetMagnify(bool v);

extern bool MNVM_GetFullScreen(void);
extern void MNVM_PostSetFullScreen(bool v);

extern bool MNVM_GetRunInBackground(void);
extern void MNVM_PostSetRunInBackground(bool v);

extern bool MNVM_GetAutoSlow(void);
extern void MNVM_PostSetAutoSlow(bool v);

/*
	Actions. These set the same request flags the emulator already
	polls, so they take effect on a following tick rather than
	immediately.
*/
extern void MNVM_PostReset(void);
extern void MNVM_PostInterrupt(void);
extern void MNVM_PostInsertDisk(void);
extern void MNVM_PostQuit(void);

/* Drives. Indices run from 0 to MNVM_GetDriveCount() - 1. */
extern int MNVM_GetDriveCount(void);
extern bool MNVM_GetDriveInserted(int driveNo);
extern bool MNVM_GetAnyDriveInserted(void);
extern void MNVM_PostEjectDrive(int driveNo);

/*
	Whether the guest has been told about the disk in a drive and so
	considers it mounted. Ejecting such a disk from the host is like
	pulling a floppy out from under the emulated Mac, so the
	interface asks first.
*/
extern bool MNVM_GetDriveMountedByGuest(int driveNo);

/*
	Copies the file name of the image in a drive, as UTF-8, into buf.
	Returns false, leaving buf unspecified, if the drive is empty,
	its name is unknown or it does not fit in bufSize bytes.
*/
extern bool MNVM_CopyDriveName(int driveNo, char *buf, int bufSize);

#ifdef __cplusplus
}
#endif

#endif /* EMUCTLAP_H */
